export const C = {
  bg:'#0f172a', card:'#1e293b', border:'#334155', text:'#f1f5f9', muted:'#94a3b8',
  dim:'#64748b', dimmer:'#475569', accent:'#6366f1', accentBg:'#312e81', accentText:'#a5b4fc',
  success:'#34d399', successBg:'#064e3b', danger:'#ef4444', warn:'#f87171', purple:'#a78bfa',
  teal:'#2dd4bf', tealBg:'#134e4a', tealDark:'#0a2020', tealText:'#99f6e4',
};

export const S = {
  cellType:  { padding:'9px 12px', color:'#a78bfa', fontSize:12 },
  cellText:  { padding:'9px 12px', color:'#f1f5f9', fontWeight:500 },
  cellMuted: { padding:'9px 12px', color:'#94a3b8' },
  cellDim:   { padding:'9px 12px', color:'#64748b', fontSize:12 },
  thBase:    { padding:'10px 12px', textAlign:'left', color:'#64748b', fontWeight:600, borderBottom:'1px solid #334155' },
  thSort:    { padding:'10px 12px', textAlign:'left', color:'#64748b', fontWeight:600, borderBottom:'1px solid #334155', cursor:'pointer', userSelect:'none' },
  tagW:      { borderRadius:6, padding:'3px 10px', fontSize:12, background:'#312e81', color:'#a5b4fc' },
  tagB:      { borderRadius:6, padding:'3px 10px', fontSize:12, background:'#134e4a', color:'#99f6e4' },
  tagCal:    { borderRadius:6, padding:'3px 10px', fontSize:12, background:'#1e293b', color:'#34d399' },
  chipW:     { display:'flex', alignItems:'center', gap:6, borderRadius:20, padding:'4px 12px', fontSize:12, background:'#312e81', border:'1px solid #6366f1', color:'#a5b4fc' },
  chipB:     { display:'flex', alignItems:'center', gap:6, borderRadius:20, padding:'4px 12px', fontSize:12, background:'#134e4a', border:'1px solid #2dd4bf', color:'#99f6e4' },
  flexWrap:  { display:'flex', flexWrap:'wrap', gap:8 },
  fwb14:     { display:'flex', flexWrap:'wrap', gap:8, marginBottom:14 },
  dotRule:   { display:'flex', gap:8, padding:'4px 0' },
  rcWrapW:   { background:'#0f172a', borderRadius:12, overflow:'hidden', border:'1px solid #334155' },
  rcWrapB:   { background:'#0f172a', borderRadius:12, overflow:'hidden', border:'1px solid #2dd4bf' },
  rcHdrW:    { background:'linear-gradient(135deg,#312e81,#1e1b4b)', padding:'16px 20px' },
  rcHdrB:    { background:'linear-gradient(135deg,#134e4a,#0a2020)', padding:'16px 20px' },
  rcGrid:    { padding:20, display:'grid', gridTemplateColumns:'1fr 1fr', gap:20 },
  rcIngItem: { padding:'4px 0', color:'#cbd5e1', fontSize:13, borderBottom:'1px solid #1e293b' },
  rcIngDotW: { color:'#a78bfa', marginRight:8 },
  rcIngDotB: { color:'#2dd4bf', marginRight:8 },
  rcWfItem:  { padding:'5px 0', color:'#cbd5e1', fontSize:13, borderBottom:'1px solid #1e293b' },
  rcIngH4W:  { color:'#a78bfa', fontSize:12, textTransform:'uppercase', letterSpacing:1, marginTop:0, marginBottom:10 },
  rcIngH4B:  { color:'#2dd4bf', fontSize:12, textTransform:'uppercase', letterSpacing:1, marginTop:0, marginBottom:10 },
  rcWfH4:    { color:'#34d399', fontSize:12, textTransform:'uppercase', letterSpacing:1, marginTop:0, marginBottom:10 },
  mealCard:  { background:'#1e293b', borderRadius:16, border:'1px solid #334155', overflow:'hidden' },
  tabBar:    { display:'flex', borderBottom:'1px solid #334155' },
  tabContent:{ padding:24 },
  ovCard:    { display:'flex', justifyContent:'space-between', alignItems:'center', background:'#0f172a', borderRadius:10, padding:'14px 18px', border:'1px solid #334155' },
  ovCardB:   { display:'flex', justifyContent:'space-between', alignItems:'center', background:'#0f172a', borderRadius:10, padding:'14px 18px', border:'1px solid #2dd4bf' },
  ovRight:   { display:'flex', gap:8 },
  ovStack:   { display:'flex', flexDirection:'column', gap:10 },
  ovSecW:    { color:'#a78bfa', fontSize:12, fontWeight:700, textTransform:'uppercase', letterSpacing:1, margin:'0 0 12px' },
  ovSecB:    { color:'#2dd4bf', fontSize:12, fontWeight:700, textTransform:'uppercase', letterSpacing:1, margin:'0 0 12px' },
  grHdr:     { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:16 },
  grNote:    { marginBottom:12, padding:'8px 14px', background:'#134e4a', border:'1px solid #2dd4bf', borderRadius:8, fontSize:12, color:'#99f6e4' },
  tableWrap: { overflowX:'auto' },
  table:     { width:'100%', borderCollapse:'collapse', fontSize:13 },
  tableHdBg: { background:'#0f172a' },
  sectStack: { display:'flex', flexDirection:'column', gap:24 },
  rcStack:   { display:'flex', flexDirection:'column', gap:16 },
  histWrap:  { background:'#1e293b', borderRadius:12, overflow:'hidden', border:'1px solid #334155' },
  histWrapT: { background:'#1e293b', borderRadius:12, overflow:'hidden', border:'1px solid #2dd4bf' },
  histTable: { width:'100%', borderCollapse:'collapse', fontSize:14 },
  histHdBg:  { background:'#0f172a' },
  histBar:     { background:'#1e293b', borderRadius:12, padding:'14px 18px', marginBottom:16, border:'1px solid #334155', display:'flex', alignItems:'center', justifyContent:'space-between', flexWrap:'wrap', gap:10 },
  histBarBtns: { display:'flex', gap:8, flexWrap:'wrap' },
  batchOff:    { background:'#1c1917', border:'1px solid #57534e', borderRadius:10, padding:'10px 16px', marginBottom:16, fontSize:13, color:'#a8a29e' },
  batchOnBar:  { background:'#134e4a', border:'1px solid #2dd4bf', borderRadius:10, padding:'10px 16px', marginBottom:16, display:'flex', justifyContent:'space-between', alignItems:'center' },
  confirmRow:  { display:'flex', gap:8, alignItems:'center' },
  clearRow:    { display:'flex', justifyContent:'flex-end', marginBottom:12 },
  emptyState:  { textAlign:'center', padding:48, color:'#475569' },
  subTabBar:   { display:'flex', background:'#0f172a', borderRadius:10, padding:3, marginBottom:20, border:'1px solid #334155', gap:3 },
  wrap:        { minHeight:'100vh', background:'#0f172a', color:'#f1f5f9', fontFamily:"'Segoe UI',sans-serif", padding:'24px 16px' },
  inner:       { maxWidth:780, margin:'0 auto' },
  hdrRow:      { display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:28 },
  backBtn:     { background:'transparent', border:'1px solid #334155', borderRadius:8, color:'#94a3b8', padding:'7px 14px', fontSize:13, cursor:'pointer', marginBottom:16 },
  navBar:      { display:'flex', background:'#1e293b', borderRadius:12, padding:4, marginBottom:24, border:'1px solid #334155' },
  genPanel:    { background:'#1e293b', borderRadius:16, padding:24, marginBottom:24, border:'1px solid #334155' },
  settPanel:   { background:'#1e293b', borderRadius:14, border:'1px solid #334155', padding:20, marginBottom:20 },
  settTitle:   { color:'#e2e8f0', fontSize:13, margin:'0 0 18px', textTransform:'uppercase', letterSpacing:1, fontWeight:700 },
  settRow:     { display:'flex', gap:20, flexWrap:'wrap' },
  settDiv:     { marginTop:20, paddingTop:16, borderTop:'1px solid #334155' },
  batchSecTit: { color:'#2dd4bf', fontSize:12, fontWeight:700, textTransform:'uppercase', letterSpacing:1, margin:'0 0 14px' },
  togOn:   { display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:16, padding:'12px 16px', background:'#134e4a', border:'1px solid #2dd4bf', borderRadius:12, cursor:'pointer' },
  togOff:  { display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:16, padding:'12px 16px', background:'#0f172a', border:'1px solid #334155', borderRadius:12, cursor:'pointer' },
  trackOn:  { width:44, height:24, borderRadius:12, background:'#2dd4bf', position:'relative', flexShrink:0 },
  trackOff: { width:44, height:24, borderRadius:12, background:'#475569', position:'relative', flexShrink:0 },
  thumbOn:  { position:'absolute', top:2, left:22, width:20, height:20, borderRadius:10, background:'#fff', transition:'left 0.2s' },
  thumbOff: { position:'absolute', top:2, left:2,  width:20, height:20, borderRadius:10, background:'#fff', transition:'left 0.2s' },
  pgMeta:  { display:'flex', alignItems:'center', justifyContent:'center', gap:10, marginBottom:10 },
  pgBar:   { width:120, height:4, background:'#1e293b', borderRadius:2, overflow:'hidden' },
  pgRow:   { display:'flex', gap:8, justifyContent:'center', flexWrap:'wrap' },
  pgPend:  { display:'flex', alignItems:'center', gap:6, padding:'6px 14px', background:'#0f172a', border:'1px solid #334155', borderRadius:8, fontSize:13, color:'#64748b' },
  pgDone:  { display:'flex', alignItems:'center', gap:6, padding:'6px 14px', background:'#064e3b', border:'1px solid #34d399', borderRadius:8, fontSize:13, color:'#34d399' },
  pgDoneB: { display:'flex', alignItems:'center', gap:6, padding:'6px 14px', background:'#134e4a', border:'1px solid #2dd4bf', borderRadius:8, fontSize:13, color:'#2dd4bf' },
};

export const DEFAULT_RULES = [
  'High protein, high fiber. Mild spice only. Standard supermarket ingredients.',
  'Serves 2: one portion keto (no/low carb), one portion normal diet.',
  'Every recipe must include a keto swap note.',
  'Clearly note which components to separate for the keto portion.',
  'If recipe uses frozen meat, add a thawing note as the first workflow step.',
];

export const CUISINES = [
  'Japanese','Mexican','Italian','Thai','Korean','Indian','Mediterranean',
  'Chinese','Vietnamese','American','Moroccan','Greek','Brazilian','Turkish',
  'Ethiopian','Peruvian','Spanish','Lebanese','Indonesian','Cajun',
];

export const RULES_VER  = 'v3';
export const RULES_KEY  = 'settings:customRules3';
export const LEGACY_KEY = 'settings:customRules';